# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jQtzpKxQ95QH1yyUIuQUdxvobiUOKS6
"""

import csv
from datetime import datetime, timedelta

def fines(student_data, meeting_start_time, total_fine):
    meeting_time = datetime.strptime(meeting_start_time, '%H:%M')
    late_students = []
    total_late_minutes = 0

    for student in student_data:
        student_name = student['Student Name']
        arrival_time = datetime.strptime(student['Arrival Time'], '%H:%M')

        if arrival_time > meeting_time:
            minutes_late = (arrival_time - meeting_time).seconds // 60
            total_late_minutes += minutes_late

            late_students.append({
                'Student Name': student_name,
                'Minutes Late': minutes_late
            })

    if total_late_minutes > 0:
        for student in late_students:
            proportion = student['Minutes Late'] / total_late_minutes
            fine_amount = round(proportion * total_fine)
            student['Fine Amount'] = fine_amount

    return late_students

def main():
    csv_file = 'student_arrival_times.csv'
    meeting_start_time = '09:00'
    total_fine_amount = 300

    student_data = []
    with open(csv_file, mode='r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            student_data.append({
                'Student Name': row['Student Name'],
                'Arrival Time': row['Arrival Time']
            })

    late_students = fines(student_data, meeting_start_time, total_fine_amount)

    print("Student Name\tMinutes Late\tFine Amount")
    for student in late_students:
        print(f"{student['Student Name']}\t{student['Minutes Late']}\t\t{student['Fine Amount']}")

if __name__ == "__main__":
    main()